apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-mysql
  template:
    metadata:
      labels:
        app: keycloak-mysql
    spec:
      containers:
        - name: keycloak-mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: keycloak-mysql-secrets
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: keycloak-mysql-config
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: keycloak-mysql-config
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: keycloak-mysql-secrets
          volumeMounts:
            - name: keycloak-mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: keycloak-mysql-data
          persistentVolumeClaim:
            claimName: keycloak-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-mysql
spec:
  selector:
    app: keycloak-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-mysql-pv
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/keycloak/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-mysql-config
data:
  MYSQL_DATABASE: "keycloak"
  MYSQL_USER: "keycloak"
---
apiVersion: v1
data:
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  MYSQL_ROOT_PASSWORD: cm9vdA==
kind: Secret
metadata:
  name: keycloak-mysql-secrets
